### ISSUE TITLE
State-API page stuck on "Getting Ready..."

### ISSUE THREAD

**Issue by dbzx6r** [dipsylala/pwnagotchi-state-api#7]
I've been at this for a week, I've followed the instructions to a T. When attempting to access state-api page, it only displays "Getting Ready..." and does not progress past that. 

> Perform a git clone from here. The state-api.py file goes in the plugins/defaults directory, or wherever you want to put your custom plugins The files in goes_in_ui_web has to go in /usr/local/lib/python3.7/dist-packages/pwnagotchi/ui/web

I have put state-api.py into /usr/local/src/pwnagotchi/plugins/default. I have moved "static" and "templates" to /usr/local/lib/python3.7/dist-packages/pwnagotchi/ui/web. I have also individually tried to move all the files individually to those directories but no avail.  

> The _**files**_ in goes_in_ui_web.

 I'm unsure which is the correct approach as inside goes_in_ui_web contains directories, but instruction says to move the files.

**Comment by dbzx6r** [comment]
For clarification: http://172.20.10.6:8080/plugins/state-api returns "Getting Ready..."

http://172.20.10.6:8080/plugins/state-api/json returns an error.

**Comment by dipsylala** [comment]
Hey - apologies, but this repo can be considered unsupported. I no longer have any involvement with Pwnagotchi.
